### ISSUE TITLE
External power-supply vs Pi USB-C power

### ISSUE THREAD

**Issue by tillik** [sbcshop/UPS-Hat-RPi#5]
My UPS-hat seems to work as expected, but unfortunately I find the documentation a little sparse.
How is the Power supply supposed to work? Will the batteries also be charged when the Pi is powered via USB-C?
Or do I need to use the external power-supply for this?
What happens if I connect both the USB-C power-supply of the Pi and your external power-supply?

**Comment by tillik** [comment]
You [Youtube-Video ](https://www.youtube.com/watch?v=9vatnF2JgK8) shows charging the batteries using the external power-supply. What if someone accidentally connects both the Raspberry USB-C power as well as the external power-supply?

**Comment by tedder** [comment]
I was wondering this too. I assumed it only worked with the 8v power supply.

**Comment by sbcshop1** [comment]
@tillik  What if someone accidentally connects both the Raspberry USB-C power as well as the external power supply?
answer - Nothing will happen if you connect both type-c power as well as an external 8v adapter to UPS HAT.Raspberry pi get only 5v
